### ISSUE TITLE
Integration Test

### ISSUE THREAD

**Issue by NoCtrlZ** [PlasmNetwork/ZKRollups#10]
- [x] tester init
- [x] should execute an auto-approved deposit
- [x] should execute a normal deposit
- [x] should change pubkey onchain
- [x] should execute a transfer to new account
- [x] should execute a transfer to existing account
- [x] should execute a transfer to self
- [x] should change pubkey offchain
- [x] should test multi-transfers
- [x] should check collected fees
- [x] should fail trying to send tx with wrong signature
- [x] should execute full-exit on random wallet
- [x] should fail full-exit with wrong eth-signer
- [x] should execute a normal full-exit
- [x] should execute full-exit on an empty wallet

**Comment by NoCtrlZ** [comment]
正常なログ
```
ubuntu@ip-172-31-0-183:~$ zk test i server
yarn run v1.22.5
$ yarn workspace ts-tests test
$ zk f mocha tests/main.test.ts


  ZkSync integration tests (token: ETH, transport: HTTP)
    ✓ should execute an auto-approved deposit (2418ms)
    ✓ should execute a normal deposit (1974ms)
    ✓ should change pubkey onchain (2162ms)
    ✓ should execute a transfer to new account (582ms)
    ✓ should execute a transfer to existing account (592ms)
    ✓ should execute a transfer to self (589ms)
    ✓ should change pubkey offchain (610ms)
    ✓ should test multi-transfers (1278ms)
    1) should execute a withdrawal
    2) should execute a ForcedExit
    ✓ should check collected fees (7ms)
    ✓ should fail trying to send tx with wrong signature (109ms)
    Full Exit tests
network block skew detected; skipping block events
      ✓ should execute full-exit on random wallet (2485ms)
      ✓ should fail full-exit with wrong eth-signer (4005ms)
      ✓ should execute a normal full-exit (1952ms)
      ✓ should execute full-exit on an empty wallet (2066ms)

  ZkSync integration tests (token: wBTC, transport: WS)
    ✓ should execute an auto-approved deposit (4161ms)
    ✓ should execute a normal deposit (5761ms)
    ✓ should change pubkey onchain (2205ms)
    ✓ should execute a transfer to new account (196ms)
    ✓ should execute a transfer to existing account (198ms)
    ✓ should execute a transfer to self (202ms)
    ✓ should change pubkey offchain (202ms)
    ✓ should test multi-transfers (999ms)
    3) should execute a withdrawal
    4) should execute a ForcedExit
    ✓ should check collected fees (6ms)
    ✓ should fail trying to send tx with wrong signature (129ms)
    Full Exit tests
network block skew detected; skipping block events
      ✓ should execute full-exit on random wallet (2301ms)
      ✓ should fail full-exit with wrong eth-signer (4003ms)
      ✓ should execute a normal full-exit (2199ms)
      ✓ should execute full-exit on an empty wallet (1598ms)


  28 passing (49m)
  4 failing

  1) ZkSync integration tests (token: ETH, transport: HTTP)
       should execute a withdrawal:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) ZkSync integration tests (token: ETH, transport: HTTP)
       should execute a ForcedExit:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  3) ZkSync integration tests (token: wBTC, transport: WS)
       should execute a withdrawal:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  4) ZkSync integration tests (token: wBTC, transport: WS)
       should execute a ForcedExit:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)



error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 4
Command: /usr/bin/node
Arguments: /usr/share/yarn/lib/cli.js test
Directory: /home/ubuntu/zksync/core/tests/ts-tests
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Child process exited with code 4
```

**Comment by NoCtrlZ** [comment]
テスト用のニーモニックじゃないと初期の残高がないかもしれない

**Comment by NoCtrlZ** [comment]
インテグレーションテストエラー
参照先はSubstrateで良いのか？
```
/app # yarn mocha -r ts-node/register 'tests/**/test-integration.ts'
yarn run v1.22.5
$ /app/node_modules/.bin/mocha -r ts-node/register 'tests/**/test-integration.ts'


  Zk Rollup Integration Test
    1) "before all" hook: create tester and test wallets for "should be pass"


  0 passing (1s)
  1 failing

  1) Zk Rollup Integration Test
       "before all" hook: create tester and test wallets for "should be pass":
     Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"execution fatal: DispatchError::Module { index: 9, error: 0, message: Some(\\\"BalanceLow\\\") }\"},\"id\":51}\n","error":{"code":-32603},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x1\",\"value\":\"0x4563918244f40000\",\"from\":\"0x17a4dc4af1faf9c3db0515a170491c37eb0373dc\",\"to\":\"0x10b48e7f74e25d4fea59acb9c80e63a02510cfe8\"}],\"id\":51,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://substrate:5000"}, tx={"to":{},"value":{"type":"BigNumber","hex":"0x4563918244f40000"},"from":"0x17a4dC4aF1FAF9c3Db0515a170491c37eb0373Dc","gasPrice":{},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.10)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
      at /app/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:204:31
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Promise.all (index 5)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NoCtrlZ** [comment]
ここのスクリプトが呼ばれる
https://github.com/matter-labs/zksync/blob/master/core/tests/ts-tests/tests/main.test.ts

**Comment by NoCtrlZ** [comment]
一つ目のテストはそもそも落ちる前提

**Comment by NoCtrlZ** [comment]
zksync.js以下にzksyncのウォレットが入っている

**Comment by NoCtrlZ** [comment]
```
ubuntu@ip-172-31-0-183:~/zksync$ zk test i server
yarn run v1.22.5
$ yarn workspace ts-tests test
$ zk f mocha tests/main.test.ts


  ZkSync integration tests (token: ETH, transport: HTTP)
receipt is here
{
  executed: true,
  block: { blockNumber: 15, committed: true, verified: false }
}
receipt is following
{
  executed: true,
  block: { blockNumber: 15, committed: true, verified: false }
}
executed
true
0 2e+21
    ✓ should execute an auto-approved deposit (2312ms)
    ✓ should change pubkey onchain (2166ms)

  ZkSync integration tests (token: wBTC, transport: WS)
receipt is here
{
  executed: true,
  block: { blockNumber: 17, committed: true, verified: false }
}
receipt is following
{
  executed: true,
  block: { blockNumber: 17, committed: true, verified: false }
}
executed
true
0 2e+21
    ✓ should execute an auto-approved deposit (2049ms)
    ✓ should change pubkey onchain (2209ms)


  4 passing (12s)

Done in 17.91s.
```

**Comment by NoCtrlZ** [comment]
サイドチェーンで残高が更新されていない

**Comment by NoCtrlZ** [comment]
オペレータがEtherを持っていない

**Comment by NoCtrlZ** [comment]
本番環境のテストログ
```
[2021-01-23T12:17:30Z DEBUG zksync_eth_sender] witness_data for block 4: , []
[2021-01-23T12:17:31Z WARN  zksync_eth_sender::gas_adjuster] Maximum possible gas price will be used: <400000000000>
[2021-01-23T12:17:31Z INFO  zksync_eth_sender] Replacing tx: hash: 0xca872b57aeab5790a311f21c89e4a486ac879f313dcff84780fd7e9deefbac9d, old_gas: 400000000000, new_gas: 400000000000, used nonce: 0, gas limit: 403516
[2021-01-23T12:17:31Z INFO  zksync_eth_sender] Stuck tx processing: sending tx for op, eth_op_id: 1; ETH tx: <hash: 0xca872b57aeab5790a311f21c89e4a486ac879f313dcff84780fd7e9deefbac9d; gas price: 400 gwei; nonce: 0>
[2021-01-23T12:17:32Z WARN  zksync_eth_sender] Error while trying to complete uncommitted op: RPC error: Error { code: ServerError(-32000), message: "insufficient funds for gas * price + value", data: None }
[2021-01-23T12:17:33Z WARN  zksync_eth_sender::gas_adjuster] Maximum possible gas price will be used: <400000000000>
[2021-01-23T12:17:33Z INFO  zksync_eth_sender] Replacing tx: hash: 0x923be8f7596eed40b39f844eebd3b732f06ed365461a7af7d14b155ff7585851, old_gas: 400000000000, new_gas: 400000000000, used nonce: 1, gas limit: 408623
[2021-01-23T12:17:33Z INFO  zksync_eth_sender] Stuck tx processing: sending tx for op, eth_op_id: 2; ETH tx: <hash: 0x923be8f7596eed40b39f844eebd3b732f06ed365461a7af7d14b155ff7585851; gas price: 400 gwei; nonce: 1>
[2021-01-23T12:17:33Z WARN  zksync_eth_sender] Error while trying to complete uncommitted op: RPC error: Error { code: ServerError(-32000), message: "insufficient funds for gas * price + value", data: None }
[2021-01-23T12:17:34Z WARN  zksync_eth_sender::gas_adjuster] Maximum possible gas price will be used: <400000000000>
[2021-01-23T12:17:34Z INFO  zksync_eth_sender] Replacing tx: hash: 0x952326b05deb0905885d5565139aa08a215388adc8a8dc20ef4495ed78764099, old_gas: 400000000000, new_gas: 400000000000, used nonce: 2, gas limit: 412614
[2021-01-23T12:17:34Z INFO  zksync_eth_sender] Stuck tx processing: sending tx for op, eth_op_id: 3; ETH tx: <hash: 0x952326b05deb0905885d5565139aa08a215388adc8a8dc20ef4495ed78764099; gas price: 400 gwei; nonce: 2>
[2021-01-23T12:17:35Z WARN  zksync_eth_sender] Error while trying to complete uncommitted op: RPC error: Error { code: ServerError(-32000), message: "insufficient funds for gas * price + value", data: None }
[2021-01-23T12:17:35Z DEBUG zksync_eth_sender] public_data for block_number 4: 020000000100004a817c800981e413a74e78b2debc913eaee3f625ac2c1b590000000003276b0000000000000000000000000000000005000000010000000000034a817c8009276b0300000001000000000000000000008ac7230489e80000276b3b7cca90f4cf62737d19bb835b3f249592bee208000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2021-01-23T12:17:35Z DEBUG zksync_eth_sender] witness_data for block 4: , []
[2021-01-23T12:17:38Z DEBUG zksync_eth_sender] public_data for block_number 4: 020000000100004a817c800981e413a74e78b2debc913eaee3f625ac2c1b590000000003276b0000000000000000000000000000000005000000010000000000034a817c8009276b0300000001000000000000000000008ac7230489e80000276b3b7cca90f4cf62737d19bb835b3f249592bee208000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2021-01-23T12:17:38Z DEBUG zksync_eth_sender] witness_data for block 4: , []
[2021-01-23T12:17:40Z INFO  zksync_core::state_keeper] Creating full block: 5, operations: 1, chunks_left: 24, miniblock iterations: 11
[2021-01-23T12:17:40Z INFO  zksync_core::committer] commit block #5
^C[2021-01-23T12:17:40Z WARN  zksync_server] Stop signal received, shutting down
```

**Comment by NoCtrlZ** [comment]
awsのテスト環境ではconfig/eth.jsonのweb3_urlを変更する必要がある

**Comment by NoCtrlZ** [comment]
ここでサイドチェーン残高を確認している
https://github.com/matter-labs/zksync/blob/master/sdk/zksync.js/src/provider.ts#L121

**Comment by NoCtrlZ** [comment]
残高の取得関数はこれっぽい
https://github.com/matter-labs/zksync/blob/master/core/bin/zksync_api/src/api_server/rpc_server/rpc_impl.rs#L29

**Comment by NoCtrlZ** [comment]
Tokenの残高はここの構造体に格納されている
https://github.com/matter-labs/zksync/blob/master/core/bin/zksync_api/src/utils/token_db_cache.rs#L15

**Comment by NoCtrlZ** [comment]
残高を確認するエンドポイント
https://github.com/matter-labs/zksync/blob/master/core/bin/zksync_api/src/core_api_client.rs#L45

**Comment by NoCtrlZ** [comment]
ここの状態からbalanceを取っている
https://github.com/matter-labs/zksync/blob/master/core/bin/zksync_api/src/api_server/rpc_server/rpc_impl.rs#L26

**Comment by NoCtrlZ** [comment]
ここでTokenCacheDBから残高を引っ張ってきている
https://github.com/matter-labs/zksync/blob/master/core/bin/zksync_api/src/api_server/rpc_server/types.rs#L37

**Comment by NoCtrlZ** [comment]
ここでトークンの残高を返している
https://github.com/matter-labs/zksync/blob/master/core/lib/types/src/account/mod.rs#L194

**Comment by NoCtrlZ** [comment]
ここでアカウントの構造体を取得している
https://github.com/matter-labs/zksync/blob/master/core/bin/zksync_api/src/api_server/rpc_server/mod.rs#L317

**Comment by NoCtrlZ** [comment]
この形式でアカウント残高が返される
https://github.com/matter-labs/zksync/blob/master/core/lib/types/src/account/mod.rs#L71

**Comment by NoCtrlZ** [comment]
ここにアカウントのデータが入っている
https://github.com/matter-labs/zksync/blob/master/core/lib/storage/migrations/2020-04-07-065600_init_storage/up.sql#L118

**Comment by NoCtrlZ** [comment]
ここで残高を挿入している
https://github.com/ArtreeTechnologies/zksync/blob/master/core/lib/storage/src/chain/state/mod.rs#L49

**Comment by NoCtrlZ** [comment]
Amountが空欄になっている
```
Block((BlockCommitRequest { block: Block { block_number: 7, new_root_hash: Fr(0x0866b50c6f996bac0f349fe84a1a8ce606579b28d9e82b779d0761727821e369), fee_account: 0, block_transactions: [PriorityOp(ExecutedPriorityOp { priority_op: PriorityOp { serial_id: 6, data: Deposit(Deposit { from: 0x17a4dc4af1faf9c3db0515a170491c37eb0373dc, token: 0, amount: BigUint { data: [] }, to: 0x31140ce45c91e2c966bcab7f2453eed80b611a2b }), deadline_block: 17299, eth_hash: [51, 15, 94, 51, 186, 34, 32, 84, 193, 224, 247, 145, 153, 122, 168, 76, 162, 161, 148, 195, 173, 49, 132, 95, 211, 158, 138, 95, 3, 130, 91, 160], eth_block: 19 }, op: Deposit(DepositOp { priority_op: Deposit { from: 0x17a4dc4af1faf9c3db0515a170491c37eb0373dc, token: 0, amount: BigUint { data: [] }, to: 0x31140ce45c91e2c966bcab7f2453eed80b611a2b }, account_id: 7 }), block_index: 0, created_at: 2021-01-25T13:47:23.406250880Z })], processed_priority_ops: (6, 7), block_chunks_size: 6, commit_gas_limit: 403516, verify_gas_limit: 1300000 }, accounts_updated: [(7, Create { address: 0x31140ce45c91e2c966bcab7f2453eed80b611a2b, nonce: 0 }), (7, UpdateBalance { old_nonce: 0, new_nonce: 0, balance_update: (0, BigUint { data: [] }, BigUint { data: [] }) })] }, AppliedUpdatesRequest { account_updates: [], first_update_order_id: 2 }))
commit_state_update
```
