### ISSUE TITLE
Milestone1

### ISSUE THREAD

**Issue by NoCtrlZ** [PlasmNetwork/ZKRollups#3]
- [x] build EVM and Web3 RPC environment
- [x] deploy ZK Rollup contract
- [x] contracts unit test
- [x] operator and prover implementation
- [x] integration test

**Comment by NoCtrlZ** [comment]
Ethereum Compatibility Pallet
https://github.com/paritytech/frontier

**Comment by NoCtrlZ** [comment]
送金のテストが通らない

**Comment by NoCtrlZ** [comment]
# zksync_server --genesis
GENESIS_ROOT=0x24fb8350686446796e71ca3f33d4e256aa3c6bee7bb19fbbff2540de71bb22ba
thread 'main' panicked at 'Initial token list not found: No such file or directory (os error 2)', /usr/src/zksync/core/bin/zksync_core/src/lib.rs:103:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by NoCtrlZ** [comment]
Operatorのコンテナが起動しない。
--genesisのコマンドを実行していないことが原因と考えられる。
しかし、--genesisコマンドを実行した際に上記のエラーが出力される。

**Comment by NoCtrlZ** [comment]
Operatorのコンテナが起動できた
次にインテグレーションテストを開始する

**Comment by NoCtrlZ** [comment]
インテグレーションテストのログ
```
ubuntu@ip-172-31-0-183:~$ zk test i server
yarn run v1.22.5
$ yarn workspace ts-tests test
$ zk f mocha tests/main.test.ts


  ZkSync integration tests (token: ETH, transport: HTTP)
    ✓ should execute an auto-approved deposit (2418ms)
    ✓ should execute a normal deposit (1974ms)
    ✓ should change pubkey onchain (2162ms)
    ✓ should execute a transfer to new account (582ms)
    ✓ should execute a transfer to existing account (592ms)
    ✓ should execute a transfer to self (589ms)
    ✓ should change pubkey offchain (610ms)
    ✓ should test multi-transfers (1278ms)
    1) should execute a withdrawal
    2) should execute a ForcedExit
    ✓ should check collected fees (7ms)
    ✓ should fail trying to send tx with wrong signature (109ms)
    Full Exit tests
network block skew detected; skipping block events
      ✓ should execute full-exit on random wallet (2485ms)
      ✓ should fail full-exit with wrong eth-signer (4005ms)
      ✓ should execute a normal full-exit (1952ms)
      ✓ should execute full-exit on an empty wallet (2066ms)

  ZkSync integration tests (token: wBTC, transport: WS)
    ✓ should execute an auto-approved deposit (4161ms)
    ✓ should execute a normal deposit (5761ms)
    ✓ should change pubkey onchain (2205ms)
    ✓ should execute a transfer to new account (196ms)
    ✓ should execute a transfer to existing account (198ms)
    ✓ should execute a transfer to self (202ms)
    ✓ should change pubkey offchain (202ms)
    ✓ should test multi-transfers (999ms)
    3) should execute a withdrawal
    4) should execute a ForcedExit
    ✓ should check collected fees (6ms)
    ✓ should fail trying to send tx with wrong signature (129ms)
    Full Exit tests
network block skew detected; skipping block events
      ✓ should execute full-exit on random wallet (2301ms)
      ✓ should fail full-exit with wrong eth-signer (4003ms)
      ✓ should execute a normal full-exit (2199ms)
      ✓ should execute full-exit on an empty wallet (1598ms)


  28 passing (49m)
  4 failing

  1) ZkSync integration tests (token: ETH, transport: HTTP)
       should execute a withdrawal:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) ZkSync integration tests (token: ETH, transport: HTTP)
       should execute a ForcedExit:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  3) ZkSync integration tests (token: wBTC, transport: WS)
       should execute a withdrawal:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  4) ZkSync integration tests (token: wBTC, transport: WS)
       should execute a ForcedExit:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)



error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 4
Command: /usr/bin/node
Arguments: /usr/share/yarn/lib/cli.js test
Directory: /home/ubuntu/zksync/core/tests/ts-tests
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Child process exited with code 4
```
